### ISSUE TITLE
Board AB02A can not be selected in IDE 2.3.3 (nor in IDE 1.8,.19)

### ISSUE THREAD

**Issue by sterretjeToo** [HelTecAutomation/CubeCell-Arduino#291]
This issue report is triggered by https://forum.arduino.cc/t/board-for-htcc-ab02a/1317566/ where a user sees the board but selecting it does not result in the board being selected.

This issue was first reported on https://github.com/arduino/arduino-cli/issues/2742 which referred me to this issue tracker.

![image](https://github.com/user-attachments/assets/b8a8b18b-b160-4452-a3ef-e4e3bfb0ca77)

After installing version 1.5.0 of the Cubecell Development Framework  in Arduino IDE 2.3.3 one is not able to select the `CubeCell-1/2AA Node（HTCC-AB02A）` board. The board can be seen in Tools/Board in the IDE but can not be selected.

I've confirmed the issue on a Win11 home system. The board ID `CubeCell-1/2AA` contains an invalid character '/'. See https://arduino.github.io/arduino-cli/dev/FAQ/#whats-the-fqbn-string.

Changing the board ID for the AB02A from `CubeCell-1/2AA` to e.g. `CubeCell-1-2AA` solves this issue.

```text
CubeCell-1-2AA.name=CubeCell-1/2AA Node（HTCC-AB02A）

CubeCell-1-2AA.upload.tool=CubeCellflash
CubeCell-1-2AA.upload.maximum_size=131072
...
...
```

**Comment by jotorral** [comment]
I couldn't select this board in Arduino in a Mac computer. I have tried this solution (in the file boards.txt) and it has solved the problem.

**Comment by hfs** [comment]
For me the whole “Select other board and port…” dialog broke and did not display any boards any longer.

This was logged in the console:

```
2026-04-23T11:20:52.162Z root ERROR l: Invalid FQBN: CubeCell:CubeCell:CubeCell-1/2AA
    at new s (file:///tmp/.mount_arduinHC7cj0/resources/app/lib/frontend/bundle.js:2:13225748)
    at w (file:///tmp/.mount_arduinHC7cj0/resources/app/lib/frontend/bundle.js:2:11102712)
    at a (file:///tmp/.mount_arduinHC7cj0/resources/app/lib/frontend/bundle.js:2:11102018)
    at file:///tmp/.mount_arduinHC7cj0/resources/app/lib/frontend/bundle.js:2:11102227
    at Array.map (<anonymous>)
    at e.decorateBoards (file:///tmp/.mount_arduinHC7cj0/resources/app/lib/frontend/bundle.js:2:11102117)
    at c.renderBoards (file:///tmp/.mount_arduinHC7cj0/resources/app/lib/frontend/bundle.js:2:9423510)
    at c.renderContainer (file:///tmp/.mount_arduinHC7cj0/resources/app/lib/frontend/bundle.js:2:9423259)
    at c.render (file:///tmp/.mount_arduinHC7cj0/resources/app/lib/frontend/bundle.js:2:9422845)
    at Da (file:///tmp/.mount_arduinHC7cj0/resources/app/lib/frontend/bundle.js:2:1811530)
2026-04-23T11:20:52.162Z root ERROR Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at pl (file:///tmp/.mount_arduinHC7cj0/resources/app/lib/frontend/bundle.js:2:1828986)
    at ul (file:///tmp/.mount_arduinHC7cj0/resources/app/lib/frontend/bundle.js:2:1828690)
    at pl (file:///tmp/.mount_arduinHC7cj0/resources/app/lib/frontend/bundle.js:2:1829761)
    at ml (file:///tmp/.mount_arduinHC7cj0/resources/app/lib/frontend/bundle.js:2:1830249)
    at fl (file:///tmp/.mount_arduinHC7cj0/resources/app/lib/frontend/bundle.js:2:1831698)
    at file:///tmp/.mount_arduinHC7cj0/resources/app/lib/frontend/bundle.js:2:1845450
    at Cc (file:///tmp/.mount_arduinHC7cj0/resources/app/lib/frontend/bundle.js:2:1845998)
    at oc (file:///tmp/.mount_arduinHC7cj0/resources/app/lib/frontend/bundle.js:2:1838562)
    at _ (file:///tmp/.mount_arduinHC7cj0/resources/app/lib/frontend/bundle.js:2:8409106)
    at M (file:///tmp/.mount_arduinHC7cj0/resources/app/lib/frontend/bundle.js:2:8409638)
2026-04-23T11:20:54.277Z root ERROR l: Invalid FQBN: CubeCell:CubeCell:CubeCell-1/2AA
    at s (file:///tmp/.mount_arduinHC7cj0/resources/app/lib/frontend/bundle.js:2:13225748)
    at w (file:///tmp/.mount_arduinHC7cj0/resources/app/lib/frontend/bundle.js:2:11102712)
    at a (file:///tmp/.mount_arduinHC7cj0/resources/app/lib/frontend/bundle.js:2:11102018)
    at file:///tmp/.mount_arduinHC7cj0/resources/app/lib/frontend/bundle.js:2:11102227
    at Array.map (<anonymous>)
    at e.decorateBoards (file:///tmp/.mount_arduinHC7cj0/resources/app/lib/frontend/bundle.js:2:11102117)
    at c.renderBoards (file:///tmp/.mount_arduinHC7cj0/resources/app/lib/frontend/bundle.js:2:9423510)
    at c.renderContainer (file:///tmp/.mount_arduinHC7cj0/resources/app/lib/frontend/bundle.js:2:9423259)
    at c.render (file:///tmp/.mount_arduinHC7cj0/resources/app/lib/frontend/bundle.js:2:9422845)
    at Da (file:///tmp/.mount_arduinHC7cj0/resources/app/lib/frontend/bundle.js:2:1811530)
```

The solution was to edit the file `~/.arduino15/packages/CubeCell/hardware/CubeCell/1.5.0/boards.txt` like mentioned above.
